version: 2
updates:
  # Enable version updates for npm (root package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"

  # Backend package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automerge"

  # Frontend package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "automerge"

  # Shared package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "deps(shared)"
      include: "scope"
    labels:
      - "dependencies"
      - "shared"
      - "automerge"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    assignees:
      - "jagiraud"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
