version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "7071:7071"  # Azure Functions
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/*/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mealplanner_dev
      POSTGRES_USER: mealplanner
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
